### PR TITLE
Migrated to Reaktive V2

### LINKED ISSUE #104: [4.0] Update version of badoo reaktive

### PR DESCRIPTION
**Pull request by acousticksan**
Closes #104

### CODE REVIEW

**Comment by arkivanov** [comment]
Thanks for the PR! Could you please also run `./gradlew :mvikotlin-extensions-reaktive:apiDump` and commit all updated API files? Without it the build won't pass.

**Comment by acousticksan** [comment]
Ready

**Comment by arkivanov** [comment]
It seems we should also update some tests. Could you please take a look?

```
e: file:///home/runner/work/MVIKotlin/MVIKotlin/rx-internal/src/commonTest/kotlin/com/arkivanov/mvikotlin/rx/internal/AbstractThreadingTest.kt:38:70 No value passed for parameter 'timeout'
e: file:///home/runner/work/MVIKotlin/MVIKotlin/rx-internal/src/commonTest/kotlin/com/arkivanov/mvikotlin/rx/internal/AbstractThreadingTest.kt:38:22 Cannot find a parameter with this name: timeoutMillis

e: file:///home/runner/work/MVIKotlin/MVIKotlin/rx-internal/src/commonTest/kotlin/com/arkivanov/mvikotlin/rx/internal/AbstractThreadingTest.kt:38:70 No value passed for parameter 'timeout'
```

**Comment by acousticksan** [comment]
Fixed

**Review by arkivanov — APPROVED** [review]

**Comment by arkivanov** [comment]
Thank you!

**Pull request merged**
